/** @type {import('tailwindcss').Config} */
export default {
  content: [
    "./index.html",
    "./src/**/*.{js,ts,jsx,tsx}",
  ],
  darkMode: "class",
  theme: {
    extend: {
      colors: {
        "brand-primary": "#f08c8c",
        "brand-secondary": "#84d5cd",
        "brand-primary-muted": "#544242",
        "brand-secondary-muted": "#006a65",
        "surface-container": "#1e2024",
        "on-primary": "#5c181c",
        "surface-container-highest": "#333539",
        "surface-container-low": "#1a1c20",
        "surface-lowest": "#0c0e12",
        "error": "#ffb4ab",
        "on-tertiary-fixed-variant": "#414750",
        "surface-dim": "#111317",
        "on-surface": "#e2e2e8",
        "secondary-fixed": "#9ff1ea",
        "on-tertiary-fixed": "#161c24",
        "on-secondary-fixed": "#00201e",
        "primary-fixed-dim": "#f08c8c",
        "tertiary-fixed-dim": "#c1c7d1",
        "surface-base": "#111317",
        "surface-container-high": "#282a2e",
        "on-surface-variant": "#dac1c0",
        "background": "#111317",
        "inverse-primary": "#974546",
        "secondary-container": "#006a65",
        "on-tertiary-container": "#373d46",
        "on-error-container": "#ffdad6",
        "outline": "#a28b8b",
        "on-secondary-container": "#96e7e0",
        "on-tertiary": "#2b3139",
        "on-primary-fixed-variant": "#792e31",
        "outline-variant": "#544242",
        "status-error": "#ffb4ab",
        "secondary-fixed-dim": "#84d5cd",
        "inverse-surface": "#e2e2e8",
        "surface-tint": "#f08c8c",
        "inverse-on-surface": "#2f3035",
        "surface-container-lowest": "#0c0e12",
        "on-secondary-fixed-variant": "#00504c",
        "on-secondary": "#003734",
        "on-primary-container": "#6d2528",
        "on-primary-fixed": "#3f0309",
        "on-error": "#690005",
        "primary": "#f08c8c",
        "status-success": "#84d5cd",
        "surface-bright": "#37393e",
        "tertiary-fixed": "#dde3ed",
        "primary-container": "#d97979",
        "surface": "#111317",
        "status-warning": "#f08c8c",
        "status-accent": "#f08c8c",
        "status-info": "#84d5cd",
        "border-muted": "#333539",
        "surface-variant": "#333539",
        "tertiary": "#c1c7d1",
        "surface-elevated": "#1a1c20",
        "primary-fixed": "#ffdad9",
        "border-subtle": "#252b33",
        "tertiary-container": "#a2a8b2",
        "secondary": "#84d5cd",
        "on-background": "#e2e2e8",
        "error-container": "#93000a"
      },
      borderRadius: {
        "sm": "0.125rem",
        "DEFAULT": "0.25rem",
        "md": "0.375rem",
        "lg": "0.5rem",
        "xl": "0.75rem",
        "full": "9999px"
      },
      spacing: {
        "element-gap-md": "16px",
        "unit": "4px",
        "gutter": "1.5rem",
        "margin-page": "2rem",
        "sidebar-width": "200px",
        "content-max-width": "900px",
        "element-gap-xs": "4px",
        "element-gap-sm": "8px",
        "container-max": "1440px"
      },
      fontFamily: {
        "body-lg": ["Geist"],
        "body-md": ["Geist"],
        "headline-md": ["Geist"],
        "headline-lg-mobile": ["Geist"],
        "display": ["Geist"],
        "mono-sm": ["JetBrains Mono"],
        "label-mono": ["JetBrains Mono"],
        "headline-lg": ["Geist"],
        "label-caps": ["JetBrains Mono"],
        "body-sm": ["Geist"]
      },
      fontSize: {
        "display": ["48px", { "lineHeight": "1.2", "letterSpacing": "-0.02em", "fontWeight": "600" }],
        "headline-lg": ["24px", { "lineHeight": "32px", "fontWeight": "500" }],
        "headline-md": ["18px", { "lineHeight": "24px", "fontWeight": "500" }],
        "body-lg": ["16px", { "lineHeight": "24px", "fontWeight": "400" }],
        "body-md": ["14px", { "lineHeight": "20px", "fontWeight": "400" }],
        "label-mono": ["12px", { "lineHeight": "16px", "letterSpacing": "0.05em", "fontWeight": "400" }],
        "headline-lg-mobile": ["20px", { "lineHeight": "28px", "fontWeight": "500" }],
        "mono-sm": ["12px", { "lineHeight": "16px", "letterSpacing": "0.05em", "fontWeight": "400" }],
        "label-caps": ["12px", { "lineHeight": "16px", "letterSpacing": "0.05em", "fontWeight": "400" }],
        "body-sm": ["14px", { "lineHeight": "20px", "fontWeight": "400" }]
      }
    },
  },
  plugins: [
    require('@tailwindcss/container-queries'),
    require('@tailwindcss/forms')
  ],
}
