/** @type {import('tailwindcss').Config} */
export default {
  content: [
    "./index.html",
    "./src/**/*.{js,ts,jsx,tsx}",
  ],
  darkMode: "class",
  theme: {
    extend: {
      colors: {
        "brand-primary": "#ffffff",
        "brand-secondary": "#c8c6c5",
        "brand-primary-muted": "#353534",
        "brand-secondary-muted": "#201f1f",
        "surface-container": "#201f1f",
        "on-primary": "#2f3131",
        "surface-container-highest": "#353534",
        "surface-container-low": "#1c1b1b",
        "surface-lowest": "#050505",
        "error": "#ffb4ab",
        "on-tertiary-fixed-variant": "#454747",
        "surface-dim": "#131313",
        "on-surface": "#e5e2e1",
        "secondary-fixed": "#e5e2e1",
        "on-tertiary-fixed": "#1a1c1c",
        "on-secondary-fixed": "#1b1b1c",
        "primary-fixed-dim": "#c6c6c7",
        "tertiary-fixed-dim": "#c6c6c7",
        "surface-base": "#0a0a0a",
        "surface-container-high": "#2a2a2a",
        "on-surface-variant": "#c4c7c8",
        "background": "#131313",
        "inverse-primary": "#5d5f5f",
        "secondary-container": "#474746",
        "on-tertiary-container": "#636565",
        "on-error-container": "#ffdad6",
        "outline": "#8e9192",
        "on-secondary-container": "#b7b5b4",
        "on-tertiary": "#2f3131",
        "on-primary-fixed-variant": "#454747",
        "outline-variant": "#444748",
        "status-error": "#f43f5e",
        "secondary-fixed-dim": "#c8c6c5",
        "inverse-surface": "#e5e2e1",
        "surface-tint": "#c6c6c7",
        "inverse-on-surface": "#313030",
        "surface-container-lowest": "#0e0e0e",
        "on-secondary-fixed-variant": "#474746",
        "on-secondary": "#303030",
        "on-primary-container": "#636565",
        "on-primary-fixed": "#1a1c1c",
        "on-error": "#690005",
        "primary": "#ffffff",
        "status-success": "#10b981",
        "surface-bright": "#3a3939",
        "tertiary-fixed": "#e2e2e2",
        "primary-container": "#e2e2e2",
        "surface": "#131313",
        "status-warning": "#f59e0b",
        "status-accent": "#7b61ff",
        "status-info": "#6366f1",
        "border-muted": "#333333",
        "surface-variant": "#353534",
        "tertiary": "#ffffff",
        "surface-elevated": "#111111",
        "primary-fixed": "#e2e2e2",
        "border-subtle": "#1f1f1f",
        "tertiary-container": "#e2e2e2",
        "secondary": "#c8c6c5",
        "on-background": "#e5e2e1",
        "error-container": "#93000a"
      },
      borderRadius: {
        "DEFAULT": "0.125rem",
        "lg": "0.25rem",
        "xl": "0.5rem",
        "full": "0.75rem"
      },
      spacing: {
        "element-gap-md": "16px",
        "unit": "4px",
        "gutter": "16px",
        "sidebar-width": "240px",
        "element-gap-xs": "4px",
        "element-gap-sm": "8px",
        "container-max": "1440px"
      },
      fontFamily: {
        "body-lg": ["Geist"],
        "headline-md": ["Geist"],
        "headline-lg-mobile": ["Geist"],
        "display": ["Geist"],
        "mono-sm": ["JetBrains Mono"],
        "headline-lg": ["Geist"],
        "label-caps": ["Geist"],
        "body-sm": ["Geist"]
      },
      fontSize: {
        "body-lg": ["14px", { "lineHeight": "20px", "letterSpacing": "-0.01em", "fontWeight": "400" }],
        "headline-md": ["16px", { "lineHeight": "24px", "letterSpacing": "-0.01em", "fontWeight": "500" }],
        "headline-lg-mobile": ["18px", { "lineHeight": "24px", "fontWeight": "600" }],
        "display": ["32px", { "lineHeight": "1.2", "letterSpacing": "-0.04em", "fontWeight": "600" }],
        "mono-sm": ["12px", { "lineHeight": "16px", "letterSpacing": "0", "fontWeight": "400" }],
        "headline-lg": ["20px", { "lineHeight": "28px", "letterSpacing": "-0.02em", "fontWeight": "600" }],
        "label-caps": ["11px", { "lineHeight": "16px", "letterSpacing": "0.05em", "fontWeight": "600" }],
        "body-sm": ["13px", { "lineHeight": "18px", "letterSpacing": "0", "fontWeight": "400" }]
      }
    },
  },
  plugins: [
    require('@tailwindcss/container-queries'),
    require('@tailwindcss/forms')
  ],
}
